### ISSUE TITLE
OAP not working on spark master branch and 2.0 branch.

### ISSUE THREAD

**Issue by linhong-intel** [Intel-bigdata/OAP#242]
Name: java.lang.NoSuchMethodError
Message: org.apache.spark.sql.catalyst.parser.SqlBaseParser$RelationContext.relationPrimary()Lorg/apache/spark/sql/catalyst/parser/SqlBaseParser$RelationPrimaryContext;

**Comment by adrian-wang** [comment]
OAP is not going to support an arbitrary version except those releases. There could be a lot of problems to support all Snapshots of Spark.
